home:
  path: /
  controller: App\Controller\DefaultController::index

app_login:
  path: /user
  controller: App\Controller\UserController::index
register:
  path: /register
  controller: App\Controller\UserController::register
login:
  path: /login
  controller: App\Controller\UserController::login
about-us:
  path: /abous-us
  controller: App\Controller\AboutusController::abous-us
logout:
  path: /logout
  controller: App\Controller\UserController::logout 