home:
  path: /
  controller: App\Controller\DefaultController::index

app_login:
  path: /user
  controller: App\Controller\UserController::index
register:
  path: /register
  controller: App\Controller\UserController::register
login:
  path: /login
  controller: App\Controller\UserController::login
about-us:
  path: /abous-us
  controller: App\Controller\AboutusController::abous-us
logout:
  path: /logout
  controller: App\Controller\UserController::logout 
dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::dashboard 
tables:
  path: /tables
  controller: App\Controller\DashboardController::tables
delete_user:
  path: /delete-user/{id}
  controller: App\Controller\UserController::deleteUser
profile:
  path: /profile
  controller: App\Controller\DashboardController::profile
update:
  path: /update
  controller: App\Controller\UserController::update
image:
  path: /image
  controller: App\Controller\UserController::image
add:
  path: /add
  controller: App\Controller\Coachcontroller::add

list:
  path: /list
  controller: App\Controller\Coachcontroller::list
